#!/bin/bash

cgiPath=/usr/lib/cgi-bin/

if [ ! -d "$cgiPath" ]; then
  1>2 echo "Could not find cgi directory"
  exit 1
fi


# copy cgis
sudo cp cgi/* --target-directory="$cgiPath"
sudo chown -R www-data:www-data "$cgiPath"
sudo chmod u+x "$cgiPath"/*

# copy html
sudo cp html/* --target-directory=/var/www/geeky/

# copy imgs
sudo cp data/*.png --target-directory=/var/www/geeky/img/

#vim: filetype=sh
