#!/usr/bin/env python3

import unittest
import cgi
import cgitb; cgitb.enable()

print("Content-type: text/html")
print("")

print("""
<html>
    Lore ipsum
</html>
""")

def extractKeywords():
    form = cgi.FieldStorage()


keywords = extractKeywords()

if __name__ == "__main__":
    pass

# vim: set ft=python

